name: Pull request workflow

on:
  pull_request_target:
    branches: 
      - master
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ github.run_number }}

      - name: Stop existing container
        run: docker stop simple-java-maven-app || true

      - name: Remove existing container
        run: docker rm simple-java-maven-app || true

      - name: Run new container
        run: docker run -d -p 5000:5000 --name simple-java-maven-app ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ github.run_number }}
