name: Pull request workflow

on:
  pull_request_target:
    branches: 
      - master
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Pull latest changes
       # run: git pull --rebase origin development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest

      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop simple-java-maven-app || true
            docker rm simple-java-maven-app || true
            docker run -d -p 5000:5000 --restart always --name simple-java-maven-app ${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest
