name: Push to Development Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image with multi-stage Dockerfile
        run: docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest .

      - name: Increase image tag
        id: increase_tag
        run: |
          LATEST_TAG=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          TAG="v$(echo "$LATEST_TAG" | awk -F. -v OFS=. '{$3++; print}')"
          echo "::set-output name=tag::$TAG"

      - name: Test image
        run: |
          # Run your image test commands here
          # If the tests fail, delete the new tag
          if [[ tests_failed ]]; then
            git tag -d ${{ steps.increase_tag.outputs.tag }}
            git push origin :refs/tags/${{ steps.increase_tag.outputs.tag }}
            echo "Image tests failed. Deleted the new tag."
            exit 1
          fi

      - name: Increase pom.xml version
        run: mvn versions:set -DnewVersion=$(echo $(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) | awk -F. -v OFS=. '{$3++; print}')

      - name: Push pom.xml
        run: |
          git config user.name "or-carmeli"
          git config user.email "ocarmeli7@gmail.com"
          git add pom.xml
          git commit -m "Increase pom.xml version"
          git push origin development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.increase_tag.outputs.tag }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
