name: Push to Development Pipeline

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Test
        run: mvn test
        
      - name: Increase the Patch part of the jar version
        run: mvn versions:set -DnewVersion=$(echo $(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) | awk -F. -v OFS=. '{$3++; print}')

      - name: Determine latest tag
        id: determine_latest_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=tag::$TAG"

      - name: Determine Docker image tag
        id: determine_tag
        run: |
          LATEST_TAG=$(echo "${{ steps.determine_latest_tag.outputs.tag }}" | sed 's/v//')
          TAG="v$(echo "$LATEST_TAG" | awk -F. -v OFS=. '{$3++; print}')"
          echo "::set-output name=tag::$TAG"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:${{ steps.determine_tag.outputs.tag }}
          latest-tag: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-java-maven-app:latest


      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"  
          github_token: ${{ secrets.GITHUB_TOKEN }}
